apiVersion: v1
kind: Secret
metadata:
  name: sql-secret

type: Opaque

stringData:
  DB_SERVER: abin-sql-server-2026.database.windows.net
  DB_NAME: userdb
  DB_USER: sqladmin
  DB_PASSWORD: Mysql123